DROP SCHEMA IF EXISTS data_tables CASCADE;
DROP SCHEMA IF EXISTS dict_tables CASCADE;
DROP SCHEMA IF EXISTS connect_tables CASCADE;

CREATE SCHEMA IF NOT EXISTS data_tables;
CREATE SCHEMA IF NOT EXISTS dict_tables;
CREATE SCHEMA IF NOT EXISTS connect_tables;